 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/abilities", type: :request do
  
  # Ability. As you add validations to Ability, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Ability.create! valid_attributes
      get abilities_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      ability = Ability.create! valid_attributes
      get ability_url(ability)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_ability_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      ability = Ability.create! valid_attributes
      get edit_ability_url(ability)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Ability" do
        expect {
          post abilities_url, params: { ability: valid_attributes }
        }.to change(Ability, :count).by(1)
      end

      it "redirects to the created ability" do
        post abilities_url, params: { ability: valid_attributes }
        expect(response).to redirect_to(ability_url(Ability.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Ability" do
        expect {
          post abilities_url, params: { ability: invalid_attributes }
        }.to change(Ability, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post abilities_url, params: { ability: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested ability" do
        ability = Ability.create! valid_attributes
        patch ability_url(ability), params: { ability: new_attributes }
        ability.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the ability" do
        ability = Ability.create! valid_attributes
        patch ability_url(ability), params: { ability: new_attributes }
        ability.reload
        expect(response).to redirect_to(ability_url(ability))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        ability = Ability.create! valid_attributes
        patch ability_url(ability), params: { ability: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested ability" do
      ability = Ability.create! valid_attributes
      expect {
        delete ability_url(ability)
      }.to change(Ability, :count).by(-1)
    end

    it "redirects to the abilities list" do
      ability = Ability.create! valid_attributes
      delete ability_url(ability)
      expect(response).to redirect_to(abilities_url)
    end
  end
end
